using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SlideHPbar : MonoBehaviour
{
    [SerializeField]
    private Vector3 distance = Vector3.up * 1f;
    private Transform targetTransform;
    private RectTransform rectTransform;

    public void Setup(Transform target)
    {
        targetTransform = target;
        rectTransform = GetComponent<RectTransform>();
    }
    private void LateUpdate()
    {
        if(targetTransform== null)
        {
            Destroy(gameObject);
            return;
        }
        Vector3 screenPosition = Camera.main.WorldToScreenPoint(targetTransform.position);
        rectTransform.position = screenPosition + distance;
    }

    

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
